apache/camel-examples

examples/camel-example-artemis/src/main/java/org/apache/camel/example/artemis/ArtemisMain.java
examples/camel-example-debezium/src/main/java/org/apache/camel/example/debezium/KinesisProducerToCassandra.java
examples/camel-example-ftp/src/main/java/org/apache/camel/example/ftp/MyFtpClient.java
examples/camel-example-ftp/src/main/java/org/apache/camel/example/ftp/MyFtpServer.java
examples/camel-example-kotlin/src/main/kotlin/org/apache/camel/example/MainApp.kt
examples/camel-example-loan-broker-jms/src/main/java/org/apache/camel/loanbroker/LoanBroker.java
examples/camel-example-netty-custom-correlation/src/main/java/org/apache/camel/example/netty/MyClient.java
examples/camel-example-netty-custom-correlation/src/main/java/org/apache/camel/example/netty/MyServer.java
examples/camel-example-spark-rest/src/main/java/org/apache/camel/example/spark/UserMain.java
examples/camel-example-splunk/src/main/java/org/apache/camel/example/splunk/SplunkSavedSearchClient.java
examples/camel-example-splunk/src/main/java/org/apache/camel/example/splunk/SplunkSearchClient.java
examples/camel-example-twitter-websocket/src/main/java/org/apache/camel/example/websocket/CamelTwitterWebSocketMain.java
examples/camel-example-widget-gadget-java/src/main/java/org/apache/camel/example/widget/WidgetMain.java

Hi!
It's my first contribution - let me know if something is missing or doesn't follow project contribution guidelines.
It's quite a minor change. All examples using deprecated method
org.apache.camel.main.BaseMainSupport#addRouteBuilder(org.apache.camel.RoutesBuilder) 
updated to use org.apache.camel.main.BaseMainSupport#addRoutesBuilder as suggested by documentation.

Migrate deprecated org.apache.camel.main.BaseMainSupport#addRouteBuilder(org.apache.camel.RoutesBuilder)

---

examples/camel-example-artemis/src/main/java/org/apache/camel/example/artemis/ArtemisMain.java
examples/camel-example-debezium/src/main/java/org/apache/camel/example/debezium/DebeziumMySqlConsumerToKinesis.java
examples/camel-example-debezium/src/main/java/org/apache/camel/example/debezium/KinesisProducerToCassandra.java
examples/camel-example-ftp/src/main/java/org/apache/camel/example/ftp/MyFtpClient.java
examples/camel-example-ftp/src/main/java/org/apache/camel/example/ftp/MyFtpServer.java
examples/camel-example-java8/src/main/java/org/apache/camel/example/java8/MyApplication.java
examples/camel-example-kotlin/src/main/kotlin/org/apache/camel/example/MainApp.kt
examples/camel-example-loan-broker-jms/src/main/java/org/apache/camel/loanbroker/LoanBroker.java
examples/camel-example-main-artemis/src/main/java/org/apache/camel/example/MyApplication.java
examples/camel-example-main-tiny/src/main/java/org/apache/camel/example/MyApplication.java
examples/camel-example-main-xml/src/main/java/org/apache/camel/example/MyApplication.java
examples/camel-example-main/src/main/java/org/apache/camel/example/MyApplication.java
examples/camel-example-mongodb/src/main/java/org/apache/camel/example/mongodb/Application.java
examples/camel-example-netty-custom-correlation/src/main/java/org/apache/camel/example/netty/MyClient.java
examples/camel-example-netty-custom-correlation/src/main/java/org/apache/camel/example/netty/MyServer.java
examples/camel-example-reactive-executor-vertx/src/main/java/org/apache/camel/example/MyApplication.java
examples/camel-example-splunk/src/main/java/org/apache/camel/example/splunk/SplunkSavedSearchClient.java
examples/camel-example-splunk/src/main/java/org/apache/camel/example/splunk/SplunkSearchClient.java
examples/camel-example-twitter-websocket/src/main/java/org/apache/camel/example/websocket/CamelTwitterWebSocketMain.java
examples/camel-example-widget-gadget-java/src/main/java/org/apache/camel/example/widget/WidgetMain.java

Trying to build examples for the master branch found out that the new "configure()" method was missing. So added it to make the examples buildable.

Fixed examples camel main class

---

examples/camel-example-cdi-properties/src/test/java/org/apache/camel/example/cdi/properties/CdiPropertiesTest.java
examples/camel-example-cdi-xml/src/test/java/org/apache/camel/example/cdi/xml/CdiXmlTest.java
examples/camel-example-cxf-proxy/pom.xml
examples/camel-example-cxf/pom.xml

Hello,
Changing the @Observers events from `CamelContext**Starting**Event` to `CamelContext**Started**Event` fixes the tests 
I don't know why though ... was there a change in the behavior of CamelContext Events ?

CAMEL-15379: Fix failing cdi examples tests

---

examples/camel-example-kafka/src/main/java/org/apache/camel/example/kafka/MessageConsumerClient.java

Resolving 
Error while fetching metadata with correlation id 2: {TestLog&maxPollRecords=5000&consumersCount=1&seekTo=beginning&groupId=kafkaGroup=INVALID_TOPIC_EXCEPTION}

Fix MessageConsumerClient subscription

---

examples/camel-example-spring-security/client/access-admin-as-jim.sh
examples/camel-example-spring-security/client/access-admin-no-auth.sh
examples/camel-example-spring-security/client/access-user-as-bob.sh
examples/camel-example-spring-security/client/access-user-as-jim.sh
examples/camel-example-spring-security/client/access-user-no-auth.sh

All the scripts were non-working as the context root-path was missing by all of them.
Verified the changes using `apache-tomcat-9.0.36`.

improve the scripts of camel-example-spring-security

---

examples/spring/pom.xml
examples/spring/src/test/java/org/apache/camel/example/spring/IntegrationTest.java

- Example couldn't run because of the missing dependency. In apache-camel version 3.7.x artifact camel-bean was located in camel-spring (as transitive dependency) which is not the case in the version 3.9.0-SNAPSHOT.
[ERROR] Failed to execute goal org.apache.camel:camel-maven-plugin:3.9.0-SNAPSHOT:run (default-cli) on project camel-example-spring: null: MojoExecutionException: InvocationTargetException: Failed to create route route3 at: >>> Bean[org.apache.camel.example.spring.MyRouteBuilder$SomeBean] <<< in route: Route(route3)[From[file://target/test?noop=true] -> [Bean[or... because of Cannot find BeanProcessorFactory on classpath. Add camel-bean to classpath. -> [Help 1]
- Additionally IntegrationTest was falsy correct because the argument option '"-o", "target/site/cameldoc"' caused …

Add missing camel-bean dependency

---

examples/cxf-proxy/src/main/resources/META-INF/spring/camel-config.xml

FYI: 20 years ago I used to be rleland@apache.org since I am a first time contributor, but I had them deactivate that account in 2005.

cfx-proxy: Fix Starup error because file:target/custom.properties is missing

---

examples/spring-ws/pom.xml

Removed org.springframework.ws dependency causing incompatible versions of spring jars; it's included from the camel-spring-ws component.
Added camel-core-languages dependency to fix another deployment error.
Added jdk9 profile to include jars not present and required at runtime.

CAMEL-16256: fix pom.xml to allow spring-ws example to run

---

examples/netty-custom-correlation/src/main/java/org/apache/camel/example/netty/MyClient.java
examples/netty-custom-correlation/src/main/java/org/apache/camel/example/netty/MyServer.java
examples/spring-ws/src/main/java/org/apache/camel/example/server/IncrementRoute.java

A new way of referring beans from Endpoint URIs exist and should be promoted as the old way is now deprecated according to https://camel.apache.org/manual/faq/how-do-i-configure-endpoints.html#HowdoIconfigureendpoints-ReferringbeansfromEndpointURIs
* Modifies the examples that refer to beans from an Endpoint URI to use the new prefix `#bean:`

Promote the new way to ref a bean from Endpoint URI

---

examples/cdi-test/pom.xml
examples/cdi/pom.xml
examples/fhir/pom.xml

All examples that rely on Camel CDI don't start, they fail with the following error:
```
[INFO] --- camel-maven-plugin:3.15.0-SNAPSHOT:run (default-cli) @ camel-example-cdi ---
[INFO] You can skip tests from the command line using: mvn camel:run -Dmaven.test.skip=true
[INFO] Using org.apache.camel.spring.Main to initiate a CamelContext
[INFO] Starting Camel ...
[ERROR] *************************************
[ERROR] Error occurred while running main from: org.apache.camel.spring.Main
[ERROR] 
java.lang.ClassNotFoundException: org.apache.camel.spring.Main
at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
at java.lang.ClassLoader.loadClass (ClassLoader.java:589)
at java.lang.ClassLoader.loadClass (ClassLoader.java:522)
at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:400)
at …
```

Ensure that the main class for CDI apps is called by the plugin

---

examples/jooq/pom.xml

When we launch the jOOQ example thanks to the command `mvn camel:run` with Java 11, we get the next error:
```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
at java.lang.ClassLoader.loadClass (ClassLoader.java:589)
at java.lang.ClassLoader.loadClass (ClassLoader.java:522)
at java.lang.Class.getDeclaredConstructors0 (Native Method)
at java.lang.Class.privateGetDeclaredConstructors (Class.java:3137)
at java.lang.Class.getConstructor0 (Class.java:3342)
at java.lang.Class.getDeclaredConstructor (Class.java:2553)
at org.springframework.beans.BeanUtils.instantiateClass (BeanUtils.java:146)
at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.resolve …
```

Fix the CNFE in the jOOQ example

---

examples/management/pom.xml
examples/route-throttling/pom.xml

When launching the examples `management` and `route-throttling`, we end up with an error of type:
```
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://camel.apache.org/schema/spring]
Offending resource: file [/Users/nicolasfilotto/projects/camel/camel-examples/examples/management/target/classes/META-INF/spring/camel-context.xml]
at org.springframework.beans.factory.parsing.FailFastProblemReporter.error (FailFastProblemReporter.java:72)
at org.springframework.beans.factory.parsing.ReaderContext.error (ReaderContext.java:119)
at org.springframework.beans.factory.parsing.ReaderContext.error (ReaderContext.java:111)
at …
```

Fix the BeanDefinitionParsingException in management and route-throttling examples

---

examples/main-health/src/main/java/org/apache/camel/example/MonkeyHealthCheck.java
examples/main-health/src/main/java/org/apache/camel/example/MyRouteBuilder.java

The `MonkeyHealthCheck` of the example `main-health` is always UP while it is supposed to flip between UP and DOWN.
It appears that the code actually tries to get the `MonkeyHealthCheck` instance from `HealthCheckResolver#resolveHealthCheck` which returns a different instance at each call while the correct instance is registered into the `HealthCheckRegistry`. However even if we change the code to get it from the `HealthCheckRegistry`, it doesn't work either because the routes are configured before the loading of the health checks (postProcessCamelContext vs context init).
So as workaround, this PR proposes to rely on a static field instead of a member field.
* Make the field `MonkeyHealthCheck#up` static
* Remove (incorrect) the code used to get the instance of `MonkeyHealthCheck` that …

Allow the health check to flip between UP and DOWN

---

examples/main-xml/src/main/resources/application.properties
examples/main-yaml/src/main/resources/application.properties

In the examples `main-xml` and `main-yaml`, the routes are not automatically reloaded when the route file is modified while the route reloading feature is enabled.
Since, by default the option `camel.main.routes-reload-directory-recursive` is set to `false` and the option `camel.main.routes-reload-directory` has been set to `src/main/resources`, the modifications of a file in the directory `routes` can not be detected.
* Modifies the base directory to watch in order to detect modifications in the route file.

Fix route reload configuration

---

examples/kamelet-main/src/main/resources/camel/my-route.yaml
examples/routeloader/pom.xml
examples/routeloader/src/main/resources/myroutes/my-yaml-route.yaml
examples/routes-configuration/src/main/resources/myroutes/my-yaml-route.yaml

When we try to run the example `routeloader`, we get a compilation error due to a missing dependency and if we fix it, we finally get a YAML validation error of the following type:
```
ERROR] *************************************
[ERROR] Error occurred while running main from: org.apache.camel.main.Main
[ERROR] 
java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke (Method.java:566)
at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:401)
at java.lang.Thread.run (Thread.java:829)
Caused by: …
```

Fix compilation errors in routeloader and YAML validation errors in routeloader/kamelet-main/routes-configuration

---

examples/spring-security/pom.xml

When we deploy the war file from the example spring-security, we get the next error at startup:
```
org.apache.camel.NoSuchLanguageException: No language could be found for: simple
at org.apache.camel.impl.engine.DefaultLanguageResolver.noSpecificLanguageFound(DefaultLanguageResolver.java:89) ~[camel-base-engine-3.15.0-SNAPSHOT.jar:3.15.0-SNAPSHOT]
at org.apache.camel.impl.engine.DefaultLanguageResolver.resolveLanguage(DefaultLanguageResolver.java:63) ~[camel-base-engine-3.15.0-SNAPSHOT.jar:3.15.0-SNAPSHOT]
at org.apache.camel.impl.engine.AbstractCamelContext$4.apply(AbstractCamelContext.java:1821) ~[camel-base-engine-3.15.0-SNAPSHOT.jar:3.15.0-SNAPSHOT]
at org.apache.camel.impl.engine.AbstractCamelContext$4.apply(AbstractCamelContext.java:1804) …
```

Fix NoSuchLanguageException in spring-security

---

examples/spring-xquery/src/main/resources/myTransform.xquery

The XML output file of the example `spring-xquery` doesn't seem to be what is really expected and thus should be fixed.
Indeed the expected content is:
```
<employee id="james">
<name>James Strachan</name>
<location>London</location>
</employee>
```
while the actual content is:
```
<employee id="james">
<name>
<firstName>James</firstName>
<lastName>Strachan</lastName>
</name>
<location>
<city>London</city>
</location>
</employee>
```
* Refer the text content of the target elements instead of the elements
* Add a space character between the first name and the last name.
The output file has now expected content.

Fix the content of the spring-xquery output file

---

examples/as2/src/main/resources/META-INF/spring/camel-context.xml

When try to launch the example as2, we get the next error:
```
java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke (Method.java:566)
at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:401)
at java.lang.Thread.run (Thread.java:829)
Caused by: org.apache.camel.FailedToStartRouteException: Failed to start route server-route because of null
at org.apache.camel.impl.engine.RouteService.setUp (RouteService.java:132)
at org.apache.camel.impl.engine.InternalRouteStartupManager.doInitRoutes …
```

Set the proper parameter name for the listen method in as2 example

---

examples/main-artemis/src/main/java/org/apache/camel/example/MyApplication.java
examples/main-artemis/src/main/java/org/apache/camel/example/MyConfiguration.java
examples/main-artemis/src/main/java/org/apache/camel/example/MyRouteBuilder.java
examples/main-lambda/src/main/java/org/apache/camel/example/MyApplication.java
examples/main-lambda/src/main/java/org/apache/camel/example/MyConfiguration.java
examples/main-xml/src/main/java/org/apache/camel/example/MyApplication.java
examples/main-xml/src/main/java/org/apache/camel/example/MyConfiguration.java
examples/main-yaml/src/main/java/org/apache/camel/example/MyApplication.java
examples/main-yaml/src/main/java/org/apache/camel/example/MyConfiguration.java
examples/main/src/main/java/org/apache/camel/example/MyApplication.java
examples/main/src/main/java/org/apache/camel/example/MyConfiguration.java
examples/main/src/main/resources/application.properties

The _main-xxx_ examples needs to be updated to use the updated `MainConfigurationProperties` and more specifically to remove the `MainConfigurationProperties#addConfigurationClass` configuration method that has been made private in [CAMEL-17567](https://issues.apache.org/jira/browse/CAMEL-17567).
- Update `MyConfiguration` samples configuration to implement `org.apache.camel.CamelConfiguration`
- Update `MyConfiguration#configure` configuration types signatures to match super-type
- Remove closed `MainConfigurationProperties#addConfigurationClass` usage in favor of `MainConfigurationProperties#addConfiguration`
Refs CAMEL-17567

CAMEL-17596: Fix main-xxx examples main entry

---

examples/kamelet-chucknorris/README.adoc
examples/kamelet-chucknorris/pom.xml
examples/kamelet-chucknorris/src/test/java/org/apache/camel/example/KameletChuckNorrisTest.java
examples/kamelet-main/README.adoc
examples/kamelet-main/pom.xml
examples/kamelet-main/src/test/java/org/apache/camel/example/KameletMainTest.java

Most of the Camel examples don't have any test such that they need to be launched manually to ensure that they still work which is not convenient.
* Fix the readme.doc (wording, grammar, out dated info, typos)
* Add a `finalName` in the build section of the pom of `kamelet-main` to avoid having to specify the version in the launch command of the jar
* Add statically the runtime dependencies of the Kamelet of `kamelet-main` for the test since it is dynamically managed by `DependencyDownloaderKamelet` and it is not accessible

CAMEL-11834: Add tests for Kamelet examples

---

examples/README.adoc
examples/pom.xml
examples/routetemplate-xml/README.adoc
examples/routetemplate-xml/pom.xml
examples/routetemplate-xml/src/main/java/org/apache/camel/example/MyApplication.java
examples/routetemplate-xml/src/main/resources/application.properties
examples/routetemplate-xml/src/main/resources/builders/my-template-builder.xml
examples/routetemplate-xml/src/main/resources/logback.xml
examples/routetemplate-xml/src/main/resources/templates/my-route-templates.xml
examples/routetemplate-xml/src/test/java/org/apache/camel/example/RouteTemplateXMLTest.java
examples/routetemplate/src/main/java/org/apache/camel/example/MyRouteTemplates.java
examples/routetemplate/src/main/java/org/apache/camel/example/MyTemplateBuilder.java

It is now possible to create routes from a route template using the Java and XML DSL, so let's show it.
* Modify the example `routetemplate` to use the Java DSL instead of `ConfigureRouteTemplates`/`TemplatedRouteBuilder`
* Add the new example `routetemplate-xml` to show how to create a route from route template in pure XML
* Change the simple expression in the example `routetemplate` to call the name instead of the body as probably expected originally

CAMEL-17611: Add examples to show how to use templatedRoute

---

examples/aws/main-endpointdsl-aws2-s3-kafka/src/test/java/org/apache/camel/example/AwsS3KafkaTest.java
examples/aws/main-endpointdsl-aws2-s3/src/test/java/org/apache/camel/example/AwsS3Test.java
examples/aws/main-endpointdsl-aws2/aws2-s3-events-inject/src/test/java/org/apache/camel/example/AwsS3Test.java
examples/aws/main-endpointdsl-aws2/aws2-sqs-consumer/src/test/java/org/apache/camel/example/AwsSQSTest.java
examples/aws/main-endpointdsl-kafka-aws2-s3-restarting-policy/src/test/java/org/apache/camel/example/KafkaAwsS3Test.java
examples/aws/main-endpointdsl-kafka-aws2-s3/src/test/java/org/apache/camel/example/KafkaAwsS3Test.java
examples/aws/pom.xml
examples/couchbase-log/pom.xml
examples/couchbase-log/src/test/java/org/apache/camel/example/CouchbaseTest.java
examples/debezium/pom.xml
examples/debezium/src/test/java/org/apache/camel/example/debezium/DebeziumTest.java
examples/kafka/pom.xml
examples/kafka/src/test/java/org/apache/camel/example/kafka/KafkaTest.java
examples/mongodb/pom.xml
examples/mongodb/src/test/java/org/apache/camel/example/mongodb/MongoDBTest.java
examples/vertx-kafka/pom.xml
examples/vertx-kafka/src/test/java/org/apache/camel/example/vertx/kafka/VertxKafkaTest.java

There is an extension of testcontainers for JUnit5 that we should use to simplify the test classes.
* Add the annotations specific to the testcontainers's extension
* Convert the containers into member fields

Simplify the tests by using the testcontainers' extension

---

examples/ftp/src/test/java/org/apache/camel/example/ftp/FtpTest.java
examples/kamelet/src/test/java/org/apache/camel/example/KameletTest.java
examples/main-lambda/src/test/java/org/apache/camel/example/MainLambdaTest.java
examples/main-yaml/src/test/java/org/apache/camel/example/MainYAMLTest.java
examples/main/src/test/java/org/apache/camel/example/MainTest.java

https://github.com/apache/camel/pull/6996 brings improvements like the ability to specify a main class to reduce the complexity of the test, the tests of examples should benefit from those improvements.
* Override the method `getMainClass()` to specify the main class instead of explicitly calling `withBasePackageScan(MyApplication.class.getPackageName())`
* Avoid overriding `getPropertyPlaceholderLocations` in the test `FtpTest` to specify the location of `ftp.properties` as it is already set in the `RouteBuilders`
* Use the static methods `createDirectory` and `deleteDirectory` from `TestSupport` when needed to clean up the test

CAMEL-17574: Specify a main class and avoid overriding getPropertyPlaceholderLocations 

---

examples/main-health/src/main/resources/application.properties

If we launch the example, we end up with the next error:
```
16:36:32.799 [org.apache.camel.example.MyApplication.main()] INFO  org.apache.camel.main.MainSupport - Apache Camel (Main) 3.16.0-SNAPSHOT is starting
[ERROR] *************************************
[ERROR] Error occurred while running main from: org.apache.camel.example.MyApplication
[ERROR] 
java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke (Method.java:566)
at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:410)
at java.lang.Thread.run …
```

CAMEL-17629: camel-health - Removed option to disable context health check as it should always be enabled.

---

examples/main/src/test/java/org/apache/camel/example/MainWithAnnotationTest.java

It is now possible to write a test for a Camel Main application using annotations like Spring Boot so it could be interesting to add a simple example to show how it works in practice.
* Add a new test in the example `main` corresponding to the equivalent of the existing test but with annotations.

CAMEL-17690: Add a simple test using @CamelMainTest

---

examples/jbang-kafka-health/README.adoc
examples/jbang-kafka-health/consumer.yaml
examples/jbang-kafka-health/docker-compose.yml
examples/jbang-kafka-health/producer.yaml

Kafka cannot be launched following the readme as the docker-compose file is missing.
* Add the missing docker-compose file
* Configure the default port of a Kafka broker in the routes
* Fix typos in the readme

CAMEL-17727: Add the docker-compose file in jbang-kafka-health

---

examples/main-xml/README.adoc
examples/main-xml/pom.xml
examples/main-yaml/README.adoc
examples/main-yaml/pom.xml
examples/main/README.adoc
examples/main/pom.xml

Currently, Camel textual debugging requires having camel-debug in
dependencies. This is an extra dependency that we do not want at
runtime.
Previously:
* main java example is configured having it at runtime.
* main xml and yaml doesn't have it
I think a possible good practice is to add the dependency in a profile,
for instance named `camel.debug` which can be activated with the
property camel.debug set to true.
This would be nice to be done for all examples but maybe best to start
with the 3 more simple/important main (java), main-xml and main-yaml to
help starting discussion and see the feedback on it.
I think this is even more important for 3.16 as JMX is exposed by
default when the dependency is available.
~~wondering if a note should be added in readme of the examples~~ Edit: note …

CAMEL-17821 - Provide camel-debug in a profile

---

examples/pom.xml

Related to https://issues.apache.org/jira/browse/CAMEL-18296
The tag 3.18.0 depends on a snapshot version of Camel which is unexpected, we need to propose a way to prevent it in the next releases.
* Align the versions of camel-examples with the version of camel to avoid inconsistencies

CAMEL-18296: Align camel and camel-examples versions to avoid inconsistencies

---

examples/README.adoc
examples/minio/README.adoc
examples/minio/pom.xml
examples/minio/src/main/java/org/apache/camel/example/MinioConsumer.java
examples/minio/src/main/java/org/apache/camel/example/MinioProducer.java
examples/minio/src/main/java/org/apache/camel/example/MyApplication.java
examples/minio/src/main/resources/application.properties
examples/minio/src/main/resources/logback.xml
examples/minio/src/test/java/org/apache/camel/example/MainMinioTest.java
examples/pom.xml

Add an example to show how to use the Camel MinIO component with Endpoint DSL configuration to write and read objects in a bucket. 
This example is inspired by the aws-s3 example.

Add MinIO component example with producer and consumer routes

---

main/README.adoc
main/pom.xml
main/src/main/resources/application.properties

enabled jolokia in platform-http-main

CAMEL-20253: camel-jbang - Add support for jolokia 2.x

---

as2/src/main/java/org/apache/camel/example/as2/ExamineAS2ServerEndpointExchange.java
as2/src/main/resources/META-INF/spring/camel-context.xml
resume-api/resume-api-aws2-kinesis/README.md
resume-api/resume-api-aws2-kinesis/compose.yaml
resume-api/resume-api-cassandraql/README.md
resume-api/resume-api-cassandraql/compose.yaml
resume-api/resume-api-file-offset/README.md
resume-api/resume-api-file-offset/compose.yaml
resume-api/resume-api-fileset-clusterized/README.md
resume-api/resume-api-fileset-clusterized/compose.yaml
resume-api/resume-api-fileset-wal/README.md
resume-api/resume-api-fileset-wal/compose.yaml
resume-api/resume-api-fileset/README.md
resume-api/resume-api-fileset/compose.yaml

[Migrate to Docker Compose v2](https://github.com/docker/compose/tree/main#docker-compose-v2)
Thanks !

Migrate to Docker Compose v2

---

pom.xml

main branch currently failing with:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project camel-example-aggregate-dist: Compilation failure
Error:  /home/runner/work/camel-examples/camel-examples/aggregate-dist/src/main/java/org/apache/camel/example/Application.java:[72,36] method references are not supported in -source 7
Error:    (use -source 8 or higher to enable method references)
```

Fix main build by using release configuration for maven-compiler-plugin

---

cafe/src/test/java/org/apache/camel/example/cafe/CafeRouteSpringTest.java
kafka/src/test/java/org/apache/camel/example/kafka/KafkaTest.java
main-health/src/test/java/org/apache/camel/example/MainHealthTest.java
pom.xml

* Comment out kotlin module which is no compiling. kotlin is deprecated so I do no think it is worthy to update it
* Fix compilation due to API break on test setup and tearDown method in
Camel abstract class

Fix main build

---

loadbalancing/src/main/resources/META-INF/spring/camel-route-context-loadbalancer.xml
loadbalancing/src/main/resources/META-INF/spring/camel-route-template-mina.xml

inheritErrorHandler attribute
https://camel.apache.org/manual/camel-4x-upgrade-guide-4_10.html#_xml_dsl_changes
it avoids this error:
```
java.lang.IllegalStateException: Failed to load ApplicationContext for [MergedContextConfiguration@3aefae67 testClass = org.apache.camel.example.LoadBalancingTest, locations = ["classpath:/org/apache/camel/example/test-camel-context.xml"], classes = [], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = [], contextCustomizers = [org.springframework.test.context.support.DynamicPropertiesContextCustomizer@0], contextLoader = org.apache.camel.test.spring.junit5.CamelSpringTestContextLoader, parent = null]
at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext( …
```

Fix LoadBalancerTest related to API break in Camel 4.10 and 4.8.3

---

README.adoc

it wasn't updated when as2 example was removed

Fix number of examples in readme

---

aws/main-endpointdsl-kafka-aws2-s3-restarting-policy/src/test/java/org/apache/camel/example/KafkaAwsS3Test.java
aws/main-endpointdsl-kafka-aws2-s3/src/test/java/org/apache/camel/example/KafkaAwsS3Test.java
couchbase-log/src/test/java/org/apache/camel/example/CouchbaseTest.java
csimple-joor/src/test/java/org/apache/camel/example/CSimpleJOORTest.java
csimple/src/test/java/org/apache/camel/example/CSimpleTest.java
debezium/src/test/java/org/apache/camel/example/debezium/DebeziumTest.java
ftp/src/test/java/org/apache/camel/example/ftp/FtpTest.java
main-endpointdsl/src/test/java/org/apache/camel/example/MainEndpointDSLTest.java
main-health/src/test/java/org/apache/camel/example/MainHealthTest.java
main-joor/src/test/java/org/apache/camel/example/MainJOORTest.java
main-tiny/src/test/java/org/apache/camel/example/MainTinyTest.java

useOverridePropertiesWithPropertiesComponent in Tests
it was deprecated in Camel 4.7.0
https://github.com/apache/camel/blob/0a8fc9314ccd6571e8a5686f38d381e728ab1375/components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/AbstractTestSupport.java#L339-L342

Remove usage of deprecated method
